### ISSUE TITLE
Pictures won't load

### ISSUE THREAD

**Issue by creativedamages** [karlcswanson/micboard#1]
Thanks so much for this awesome tool. I am excited to implement it in a variety of ways. Right now I can't get images to load. I don't see any file requirements other than .jpg and not image specifics as far as resolution, so not sure if that is part of my issue or not. I've tried re-installing and reboots and all that. Mac OS 10.14.6

**Comment by karlcswanson** [comment]
What are your files named as? Try an all lowercase filename.jpg

**Comment by creativedamages** [comment]
I tried this at home and the picture loaded fine. Maybe an additional reboot of my computer was all it took. I will try again once connected to devices, make sure that isn't the linchpin.

**Comment by karlcswanson** [comment]
Cool, thanks for the update.  The image list is generated each time the page is loaded, a refresh should take care of updating the images.
