### ISSUE TITLE
Safari won't refresh pictures. Chrome does.

### ISSUE THREAD

**Issue by creativedamages** [karlcswanson/micboard#11]
Mac OS X 10.14.6
Safari 12.1.2
Chrome 76.0.3809.132

**Comment by karlcswanson** [comment]
I probably need to add something in the headers to tell safari not to cache images.  For now, you can select "Show Develop menu in menu bar".  From there you can right click on the webpage to show the inspector, and refresh OR `Empty Caches` from the Develop menu.

**Comment by creativedamages** [comment]
Actually chrome is refreshing newly added pictures but not any picture edits.

**Comment by karlcswanson** [comment]
Does flushing the cache show new images? I am trying to determine if images are being cached in the browser, Micboard, or both.

From Wikipedia - 
* most Windows and Linux browsers: Hold down Ctrl and press F5.
* Safari: Hold down ⇧ Shift and click the Reload toolbar button.
* Chrome and Firefox for Mac: Hold down both ⌘ Cmd+⇧ Shift and press R.
