### ISSUE TITLE
Web interface breaks after a day or few

### ISSUE THREAD

**Issue by cxselph** [karlcswanson/micboard#12]
After leaving the server running for a day or so, the web interface acts like it doesn't have any css, etc... It resolves itself by using the restart Micboard server option in the menu. Thanks for sharing this great tool with the world.

<img width="936" alt="Screen Shot 2019-09-11 at 5 13 30 PM" src="https://user-images.githubusercontent.com/14942903/64803574-0b4f5700-d55b-11e9-85ff-c0d5833fcb3b.png">

**Comment by karlcswanson** [comment]
This might be fixed with https://github.com/karlcswanson/micboard/commit/f6555a0390970208af368f218ed3cc05f674e301.  Ill need to do some additional testing.

**Comment by cxselph** [comment]
I look forward to testing/using the new release. Love it! Thanks for all of your hard work. 

Thanks!

**Comment by karlcswanson** [comment]
No problem! Let me know if the update resolves the issue.

**Comment by cxselph** [comment]
So far so good here. 0.8.5 has been running on computer at home since the 10th and still going and I have been running it on the mac at work since saturday. I have not had to restart to get the interface to come back. I will check on it again when I get back on saturday. If all is good, I will close the issue. My team is loving it. Thanks again.

**Comment by karlcswanson** [comment]
Great, that’s good to hear! I’m glad your team is finding it useful. If you email pictures if it in action for the micboard instagram, I’ll send out some micboard stickers.

**Comment by karlcswanson** [comment]
Fixed in v0.8.5
