### ISSUE TITLE
UHF-R not connecting

### ISSUE THREAD

**Issue by dman776** [karlcswanson/micboard#17]
I have attempted to connect to a few UHF-R receivers but have not been successful.   I'm connecting ok to multiple axient receivers.
Our UHF-R's work with Wireless Workbench using the same IP as I have configured for Micboard. 

Is there a minimum firmware version needed to support UHF-R's??
My next next step is to tcpdump the IP traffic to one of the receivers to see the responses.

Any other thoughts?

**Comment by dman776** [comment]
It looks like the Pi (192.168.1.15) is sending and rec traffic to the UHFR receiver (192.168.1.17).
Micboard looks to be reporting RX_RECEIVER_COM_ERROR
[tcpdump_uhfr.txt](https://github.com/karlcswanson/micboard/files/3991699/tcpdump_uhfr.txt)

**Comment by dman776** [comment]
Here is my config.json...


`{
  "groups": [
    {
      "group": 1,
      "hide_charts": false,
      "slots": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "title": "Left Screen"
    },
    {
      "group": 2,
      "hide_charts": false,
      "slots": [
        7,
        8,
        9,
        10,
        11,
        0
      ],
      "title": "Right Screen"
    },
    {
      "group": 3,
      "hide_charts": false,
      "slots": [
        22,
        24,
        0,
        0,
        0,
        21,
        23
      ],
      "title": "Kerry Hallway"
    },
    {
      "group": 4,
      "slots": [
        4
      ],
      "title": "group 4"
    },
    {
      "group": 5,
      "slots": [
        5
      ],
      "title": "group 5"
    },
    {
      "group": 6,
      "slots": [
        6
      ],
      "title": "group 6"
    },
    {
      "group": 7,
      "slots": [
        7
      ],
      "title": "group 7"
    },
    {
      "group": 8,
      "slots": [
        8
      ],
      "title": "group 8"
    }
  ],
  "micboard_version": "0.8.5",
  "port": 8058,
  "slots": [
    {
      "chan_name_raw": "Vox 1",
      "channel": 1,
      "extended_id": "Vocal 1",
      "extended_name": "Greg",
      "ip": "192.168.1.9",
      "slot": 1,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 2",
      "channel": 2,
      "extended_id": "Vocal 2",
      "extended_name": "Janna",
      "ip": "192.168.1.9",
      "slot": 2,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 3",
      "channel": 3,
      "extended_id": "Vocal 3",
      "extended_name": "Kristy",
      "ip": "192.168.1.9",
      "slot": 3,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 4",
      "channel": 4,
      "extended_id": "Vocal 4",
      "extended_name": "Steven",
      "ip": "192.168.1.9",
      "slot": 4,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 5",
      "channel": 1,
      "extended_id": "Vocal 5",
      "extended_name": "Josh",
      "ip": "192.168.1.13",
      "slot": 5,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 6",
      "channel": 2,
      "extended_id": "Vocal 6",
      "extended_name": "Rekeshia",
      "ip": "192.168.1.13",
      "slot": 6,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 7",
      "channel": 3,
      "extended_id": "Vocal 7",
      "extended_name": "Keaton",
      "ip": "192.168.1.13",
      "slot": 7,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 8",
      "channel": 4,
      "extended_id": "Vocal 8",
      "extended_name": "Karsten",
      "ip": "192.168.1.13",
      "slot": 8,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 9",
      "channel": 1,
      "extended_id": "Vocal 9",
      "extended_name": "Mackenzie",
      "ip": "192.168.1.11",
      "slot": 9,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Vox 10",
      "channel": 2,
      "extended_id": "Vocal 10",
      "extended_name": "Ric",
      "ip": "192.168.1.11",
      "slot": 10,
      "type": "axtd"
    },
    {
      "chan_name_raw": "AcGtr 1",
      "channel": 3,
      "extended_id": "Acoustic 1",
      "extended_name": "Josh",
      "ip": "192.168.1.11",
      "slot": 11,
      "type": "axtd"
    },
    {
      "chan_name_raw": "AcGtr 2",
      "channel": 4,
      "extended_id": "Acoustic 2",
      "ip": "192.168.1.11",
      "slot": 12,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 1",
      "channel": 1,
      "extended_id": "Pack 1",
      "ip": "192.168.1.10",
      "slot": 13,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 2",
      "channel": 2,
      "extended_id": "Pack 2",
      "ip": "192.168.1.10",
      "slot": 14,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 3",
      "channel": 3,
      "extended_id": "Pack 3",
      "ip": "192.168.1.10",
      "slot": 15,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 4",
      "channel": 4,
      "extended_id": "Pack 4",
      "ip": "192.168.1.10",
      "slot": 16,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 5",
      "channel": 1,
      "extended_id": "Pack 5",
      "ip": "192.168.1.12",
      "slot": 17,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 6",
      "channel": 2,
      "extended_id": "Pack 6",
      "ip": "192.168.1.12",
      "slot": 18,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 7",
      "channel": 3,
      "extended_id": "Pack 7",
      "ip": "192.168.1.12",
      "slot": 19,
      "type": "axtd"
    },
    {
      "chan_name_raw": "Pack 8",
      "channel": 4,
      "extended_id": "Pack 8",
      "ip": "192.168.1.12",
      "slot": 20,
      "type": "axtd"
    },
    {
      "chan_name_raw": "MC 1",
      "channel": 1,
      "extended_id": "MC 1",
      "ip": "192.168.1.14",
      "slot": 21,
      "type": "axtd"
    },
    {
      "chan_name_raw": "MC 2",
      "channel": 2,
      "extended_id": "MC 2",
      "ip": "192.168.1.14",
      "slot": 22,
      "type": "axtd"
    },
    {
      "chan_name_raw": "MC 3",
      "channel": 3,
      "extended_id": "MC 3",
      "ip": "192.168.1.14",
      "slot": 23,
      "type": "axtd"
    },
    {
      "chan_name_raw": "MC 4",
      "channel": 4,
      "extended_id": "MC 4",
      "ip": "192.168.1.14",
      "slot": 24,
      "type": "axtd"
    },
    {
      "channel": 1,
      "ip": "192.168.1.17",
      "slot": 25,
      "type": "uhfr"
    },
    {
      "channel": 2,
      "ip": "192.168.1.17",
      "slot": 26,
      "type": "uhfr"
    },
    {
      "channel": 1,
      "ip": "192.168.1.18",
      "slot": 27,
      "type": "uhfr"
    },
    {
      "channel": 2,
      "ip": "192.168.1.18",
      "slot": 28,
      "type": "uhfr"
    }
  ],
  "uuid": "c97ac1d0-5e0d-4f5b-a5c6-98bcbe8008e5"
}`

**Comment by karlcswanson** [comment]
I unfortunately don’t have access to any UHFRs to test with at the moment.
The UHFR code hasn’t changed since the initial release as far as I can tell.

Can you verify that the clock is set? It will  timeout if it doesn’t hear
from a receiver in a certain amount of time.

I don’t think there has been a firmware update to the UHFRs since 2013.

I’ll be able to look closer at the code later tonight, have Christmas
service starting soon.

**Comment by dman776** [comment]
Thanks Karl.
We just finished our first Christmas service.

The firmware is the latest 1.171.0 I think.
It is working on Wireless Workbench.
I see the response traffic from it in the tcpdump that I attached to the ticket.

Not *Shure* what is happening.

Darryl

**Comment by karlcswanson** [comment]
Were these devices recently added in or are they existing ones that stopped working?  I have had another user with this same issue this past week.

So far I haven't seen anything changed in v0.85 that would affect UHFR.

If you load data.json via http://micboardIP:8058/data.json, do you see any `raw` data from the UHFR devices?  Trying to determine if micboard is partially connecting and processing data or if it is just not connecting.

**Comment by dman776** [comment]
there is no reference to the 2 uhf-r's in the data.json api output.
I've never been able to get these UHF-R's to work

**Comment by creativedamages** [comment]
FWIW, my UHF-R’s we’re working fine on .8 but have been hit or miss with this same error on .8.5. Some days they work fine, some days I get the same error as the op.

**Comment by dman776** [comment]
wondering if this is a docker container UDP issue?
I'm running the micboard server on a raspberry pi4 with docker and a micboard container.
I'll test with the native OSX server.

**Comment by karlcswanson** [comment]
Thanks for the feedback @creativedamages. I haven't heard about the UHFR issue until last week.  I developed micboard to monitor our ~24 channels of UHFR.  After about a year, that was all swapped out for Axient Digital.  Ill look around and see if I can get access to some hardware to test on.

@dman776, if you are able, can you try out the v0.8.0 and v0.8.5 mac apps?  The same config should work for both.  I am curious if v0.8.0 works with UHFR and v0.8.5 does not.  That would narrow down the issue.  Can you also close workbench?  I don't think it would affect anything, but I'd like to see if a change there is causing the issue.

I know device discovery won't work with the current docker implementation.  The container can't listen to packets on a multicast address.  Not sure if it would affect the normal UDP packets.

**Comment by dman776** [comment]
Update:

This is a Docker issue.  The Mac native app works fine.  There are issues with containers receiving UDP packets.  Since the UHF-R’s are UDP protocol, they are affected.  The Axient’s are TCP.

I’ll update with any findings after researching possible fixes for docker.

**Comment by creativedamages** [comment]
Our server is running on Mac OS. So maybe you are onto part of the problem but seems to not be a complete answer.

**Comment by karlcswanson** [comment]
@creativedamages is your firewall on? UHFR UDP behavior might be a little different.

@dman776 Glad you got it working.  Let me know what you find out about Docker.

I received a picture this week from a user with 26 channels of UHF-R.  I checked in tonight, he's been using it on a Raspberry Pi and hasn't seen these issues.
