### ISSUE TITLE
Pi install hangs on run

### ISSUE THREAD

**Issue by seansmallman** [karlcswanson/micboard#18]
Hello,
Installing Micboard on our Mac to test was a piece of cake.
I've been trying to get Micboard running on a RaspberryPi, and after multiple attempts, it always freezes at the step: $ python3 py/micboard.py

I get a GIFCHECK! and then DEBUG:Using selector: EpollSelector and then nothing.

What am I doing wrong?

**Comment by karlcswanson** [comment]
Hello Sean,
I think you may have it working.  Micboard runs in the browser.  Did you
try loading http://<your micboard ip>:8058?  From the Pi, you can access it
at http://localhost:8058

**Comment by seansmallman** [comment]
Well, you can tell I'm not that great with command-line stuff. 🤦🏼‍♂️
Yep! It's working and I was able to connect to it from another machine just fine.

Now to figure out how to auto-login ubuntu and have it auto launch.

Thanks Karl, this is an awesome little tool!!

**Comment by karlcswanson** [comment]
No problem, glad to hear you got it working.

In the docs there should be a paragraph on how to get the server part of
micboard to start at boot.

Here is a link to get Chromium started from the Raspberry Pi forums.  If
you use micboard presets, you should be able to boot right into a specific
preset.
https://www.raspberrypi.org/forums/viewtopic.php?t=235120
