### ISSUE TITLE
Can't add pictures

### ISSUE THREAD

**Issue by BroadcastBoy** [karlcswanson/micboard#24]
Hello, 
I am trying to add pictures to my config but I can not find the folder called backgrounds. In the config document it says add photos and videos to the backgrounds folder. I do not see it... am I missing something?

**Comment by karlcswanson** [comment]
What method did you use for install?
The config directory varies via OS / installation method
mac: `~/Library/Application\ Support/micboard/`
Linux: `~/.local/share/micboard/`

**Comment by BroadcastBoy** [comment]
Sorry Karl. I meant to mention that I followed the instructions for the raspberry pi install.

**Comment by karlcswanson** [comment]
Do you see anything in the `~/.local/share/micboard/` folder?  If you manually add a `backgrounds` folder there it may pick it up.

**Comment by BroadcastBoy** [comment]
Thanks Karl that was it! I was just looking in the wrong folder! Works Great. Thanks

**Comment by karlcswanson** [comment]
Awesome, glad you got it working!
