### ISSUE TITLE
RX COM Error

### ISSUE THREAD

**Issue by lazleaders** [karlcswanson/micboard#4]
![Screen Shot 2019-09-03 at 2 35 12 PM](https://user-images.githubusercontent.com/54864366/64203062-503b0580-ce58-11e9-89c8-55411fe41df1.png)
 I keep getting this every few minutes- not sure what it is thats causing this.

**Comment by karlcswanson** [comment]
Currently, if micboard doesn't hear back from a receiver within 5 seconds, it will disconnect and reconnect.  It looks like it successfully connected at one point.
Do you see any error messages in the `micboard.log` file?
This can be found in the same directory as the `config.json` file

Can you post a copy of your `config.json` file?

**Comment by lazleaders** [comment]
<img width="600" alt="Screen Shot 2019-09-08 at 10 54 11 AM" src="https://user-images.githubusercontent.com/54864366/64491481-91536100-d22e-11e9-903c-938a3a72daf2.png">






{
  "groups": [
    {
      "group": 1,
      "slots": [
        1,
        3,
        2,
        4
      ],
      "title": "Worship Leaders"
    },
    {
      "group": 2,
      "slots": [
        4,
        3,
        2,
        1
      ],
      "title": "Teachers"
    },
    {
      "group": 9,
      "slots": [
        1,
        2,
        3,
        4
      ],
      "title": "Group 9 Title"
    }
  ],
  "micboard_version": "0.8.0",
  "port": 8058,
  "slots": [
    {
      "channel": 1,
      "ip": "10.0.11.203",
      "slot": 1,
      "type": "ulxd"
    },
    {
      "channel": 2,
      "ip": "10.0.11.203",
      "slot": 2,
      "type": "ulxd"
    },
    {
      "channel": 3,
      "ip": "10.0.11.203",
      "slot": 3,
      "type": "ulxd"
    },
    {
      "channel": 4,
      "ip": "10.0.11.203",
      "slot": 4,
      "type": "ulxd"
    }
  ],
  "uuid": "3fcd6fde-79e4-48b6-bfee-62a3d3cbc63b"
}

**Comment by karlcswanson** [comment]
How long does it stay in the disconnected state?

Are these the IPs that show up in WWB for the devices?

Is the mac on the same network as the devices?
