### ISSUE TITLE
OSX Install, bad config?

### ISSUE THREAD

**Issue by srmorris2** [karlcswanson/micboard#7]
I have tried to install micboard on two different Macs with rough luck. Following in the install instructions, I never seemed to be able to get the micboard icon to come up in the menubar. When loading the default config, it seems to start, but the menubar icon does not come up. So I tried changing the default IPs to my QLXD receivers, and got the following output in terminal.

`Traceback (most recent call last):
  File "py/micboard.py", line 29, in <module>
    main()
  File "py/micboard.py", line 12, in main
    config.config()
  File "/Users/calvary/micboard/py/config.py", line 145, in config
    read_json_config(config_file())
  File "/Users/calvary/micboard/py/config.py", line 161, in read_json_config
    config_tree = json.load(config_file)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 39 column 13 (char 511)`

Then today I tried packing it into a full .app. This time I was able to get the micboard icon to come up, and even got into the web interface with the default config file, but when I changed ONLY the IP addresses to match 4 of my receivers, and restart the server, it seems to crash. .log file attached from this run.
[micboard.log](https://github.com/karlcswanson/micboard/files/3579733/micboard.log)

(Couldn't upload the json direct. [config 2.json.txt](https://github.com/karlcswanson/micboard/files/3579735/config.2.json.txt)

**Comment by cxselph** [comment]
You might try fixing the quotes around your ip addresses. Your config has strange characters instead of “”.

**Comment by cxselph** [comment]
Nevermind @srmorris2. It showed up weird on my phone. It looks fine on my desktop.

**Comment by cxselph** [comment]
@srmorris2 Ok, I just tried your config and it failed to open. I then replaced the quotes around your ips “” with regular "" quotes and it comes up just fine. Hopefully that helps you.

**Comment by srmorris2** [comment]
That was it! I wonder if its something with textedit, because I copy/pasted quotes from a different part of the file and it worked right away.

**Comment by karlcswanson** [comment]
Check Edit > Substitutions > Smart Quotes in TextEdit.  If thats on, TextEdit replaces the standard quotes with directional quotes.  This ends up creating invalid JSON that micboard can't read.

**Comment by srmorris2** [comment]
That was it! This was just a test install. When I move it over to a different machine I'll be sure thats disabled, or just install something to edit the code instead of TextEdit.
