### ISSUE TITLE
Make drag target larger for new groups

### ISSUE THREAD

**Issue by dman776** [karlcswanson/micboard#8]
When trying to add a slot to an empty group, the UI would not allow it.  If i first created a group with at least one slot (via the config.json), then I was able to add/remove slots using the group editor.

**Comment by karlcswanson** [comment]
The drop target needs to be expanded for sure.  If you drag the slot higher, towards the top of the page, does it expand?

**Comment by dman776** [comment]
ok.   It appears work on my local container if I drop it higher.   Perhaps a border around the drop target would help eliminate the user error.   Thanks.

**Comment by karlcswanson** [comment]
Fixed in 0.8.5 branch
