### ISSUE TITLE
Fix PSM1000 device ID in documentation 

### ISSUE THREAD

**Issue by creativedamages** [karlcswanson/micboard#9]
Failed to open page. Log file shows it's been trying to open data.json with no luck. One computer is doing it that was working previously and a second computer that is a fresh install.

**Comment by karlcswanson** [comment]
Can you post your `config.json` file? An error in there will prevent Micboard from launching.

If you edited `config.json` with TextEdit, make sure that `Edit > Substitutions > Smart Quotes` is turned off.  This feature changes quotes do directional quotes.  This creates an invalid JSON file that Micboard can't read.

**Comment by creativedamages** [comment]
I figured that was the case but what threw me was when it happened on a second machine without touching the config. Attached is my file. 
[config.json.zip](https://github.com/karlcswanson/micboard/files/3586070/config.json.zip)

**Comment by karlcswanson** [comment]
`channel` refers to the channel on the receiver.  It should go 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 1, 2, 1, 2, 1, 2...

**Comment by creativedamages** [comment]
Oh duh. Ok I fixed that, still no luck.

**Comment by karlcswanson** [comment]
Can you past the output of the log file?

**Comment by creativedamages** [comment]
[micboard.log](https://github.com/karlcswanson/micboard/files/3586085/micboard.log)

**Comment by creativedamages** [comment]
FWIW: Interestingly.. the "about" won't open either. just an empty window. no content.

**Comment by karlcswanson** [comment]
can you ping localhost?

If you can't, turn on filesharing in system preferences and relaunch micboard.

**Comment by creativedamages** [comment]
I can ping localhost even with file sharing turned off. I turned it on and relaunched micboard but it still isn't working.

**Comment by karlcswanson** [comment]
It looks like the web server process is stopping.  It can't resolve itself.

Whats in `/etc/hosts`?

```
2019-09-05 21:02:16,692 ERROR:Uncaught exception GET /data.json (::1)
HTTPServerRequest(protocol='http', host='localhost:8058', method='GET', uri='/data.json', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "tornado/web.py", line 1697, in _execute
  File "tornado_server.py", line 57, in get
  File "tornado_server.py", line 38, in micboard_json
  File "tornado_server.py", line 26, in localURL
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
2019-09-05 21:02:16,694 ERROR:500 GET /data.json (::1) 5.74ms
2019-09-05 21:17:42,009 DEBUG:write: 192.168.6.113 data: < GET 1 CHAN_NAME >
```

**Comment by creativedamages** [comment]
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

**Comment by creativedamages** [comment]
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

**Comment by karlcswanson** [comment]
Can you try [this](https://stackoverflow.com/a/43549848)?

**Comment by creativedamages** [comment]
If I'm doing it right it's not fixing it.

**Comment by karlcswanson** [comment]
Sorry about the hassle.  I think i have a temporary fix, what version of MacOS are you running?

**Comment by creativedamages** [comment]
No sweat! I love helping to troubleshoot. I’m grateful for your time helping the Church and beyond. This system is Mojave 10.14.6. The other system I was trying I think was Yosemite but I’m away from the office now to verify.

**Comment by karlcswanson** [comment]
Lets give this build a try

https://micboard.io/builds/Micboard%20Server-0.8.5-mac.zip

**Comment by creativedamages** [comment]
No luck. If a reboot is in order I can try that in an hour or so.

**Comment by karlcswanson** [comment]
Dang. I’ll pull out a 10.14 image this weekend to test with. 2 more things
to double check. Is the firewall off? Does http://127.0.0.1:8058 work?

**Comment by creativedamages** [comment]
Firewall is off. Unfortunately the IP hyperlink didn’t work either. Crazy that this was working fine till today. Config file is the only thing I changed. If you ever want to teamviewer in we can set that up.

**Comment by karlcswanson** [comment]
So it was working before? Can you delete or rename the log file and restart
micboard. What are the contents of the log file after the restart?

**Comment by creativedamages** [comment]
Yea it was working a treat. Just tried that.. no output of any kind in new log file.

**Comment by karlcswanson** [comment]
Can you try ‘p10t’ for the device type for your IEMs?

**Comment by creativedamages** [comment]
And we're in business!

**Comment by karlcswanson** [comment]
Great! Sorry about that, I’ll get that fixed in documentation. Thanks for
helping troubleshoot!

**Comment by creativedamages** [comment]
Np! Thanks again.
